# Generated by Django 3.0.8 on 2020-08-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200803_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
